### PR TITLE
Fixed issues with print output of configuration settings.

### PR DESCRIPTION
**Pull request by DrPennybags**
I fixed the issues with printing configuration settings to the console.
I added a null check for response back.

### CODE REVIEW

**Comment by jhuckaby** [comment]
Thank you for the null check!  But why did you change all my ANSI text coloring?  I don't want those lines to be bold, only the labels at the start, hence the mix of bold() and gray() separately.

**Comment by DrPennybags** [comment]
There is absolutely no reason other than lazy copy/paste.

**Comment by DrPennybags** [comment]
Sorry... misunderstood your response. The mix of bold and gray did not work. I (lazy) just stuck the data into a bold.gray() to move it forward. I'm sorry about missing the formatting you were going for.

**Comment by jhuckaby** [comment]
No worries at all.  If you modify your PR to only include the null check fix, I would be happy to merge it.  The mix of bold and gray seems to work fine for me:

Screen Shot 2019-09-03 at 9 32 50 AM

Perhaps it depends on the terminal app?

**Comment by DrPennybags** [comment]
I'm taking a huge guess but maybe it is due to Windows 7. What I did is separate the bold "labels" from the non-bold "values". This now displays the data and hopefully the formatting for non-Windows 7 machines.

**Comment by jhuckaby** [comment]
This PR looks like a repeat of #3.

I will implement some of these changes separately and credit you on the commits.  I cannot merge this PR as is, as it has way too many random unrelated changes, but thank you for the contributions!

**Pull request closed without merging**
